### PR TITLE
kedro 0.19.3 dependency

### PR DESCRIPTION
**Pull request by Neuron1c**
#### Description

Update version of kedro. Brings kedro-vertex in line with current version of kedro. Allows the use of the kedro-datasets package for more minimal implementations.

##### PR Checklist
- [✅ ] Tests added
- [✅ ] [Changelog](CHANGELOG.md) updated

### CODE REVIEW

**Comment by mwiewior** [comment]
hey @Neuron1c thanks for this PR - let me check that and come back to you!

**Comment by Lasica** [comment]
Pre-commit hooks don't pass.
```
[INFO] This may take a few minutes...
isort....................................................................Failed
- hook id: isort
- files were modified by this hook

Fixing /home/runner/work/kedro-vertexai/kedro-vertexai/kedro_vertexai/context_helper.py

black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted kedro_vertexai/grouping.py
```
I'll review the code tomorrow, but you can help me out by doing `pre-commit install` and `pre-commit run` and fix issues/commit black formatting fixes.

**Comment by Lasica** [comment]
Also e2e tests need fixing in the new kedro.

**Comment by Lasica** [comment]
Ok I think the simplest will be if I merge the PR and fix the issues in separate PR.

Thanks again for your contribution :)

**Comment by Neuron1c** [comment]
I forgot the pre-commit hooks. Rookie hour here, first PR to a public repo. Thanks for the plugin and let me know if there is anything I need to do

**Comment by Lasica** [comment]
Thanks for you contribution!

I resolved the underlying issues in separate PR pulling from your branch. I've squashed the commits so you can pull with override from main on your fork again.
https://github.com/getindata/kedro-vertexai/pull/143

**Pull request closed without merging**
